### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by tyvdh** [stellarguard/stellar-uri#3]
* **I'm submitting a ...**
[x] bug report
[] feature request
[] question about the decisions made in the repository
[] question about how to use this project

* **Summary**
Trying to create a uri from a transaction object and getting the error

```
ReferenceError: URL is not defined
    at new TransactionStellarUri (/Users/tyler/Desktop/Web/StellarAuth/stellarauth-serverless/.webpack/service/webpack:/node_modules/@stellarguard/stellar-uri/build/module/lib/transaction-stellar-uri.js:17:1)
    at Function.forTransaction (/Users/tyler/Desktop/Web/StellarAuth/stellarauth-serverless/.webpack/service/webpack:/node_modules/@stellarguard/stellar-uri/build/module/lib/transaction-stellar-uri.js:9:1)
    at forTransaction (/Users/tyler/Desktop/Web/StellarAuth/stellarauth-serverless/.webpack/service/webpack:/handler.js:185:41)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Looks like the URL package is missing somewhere.

https://github.com/stellarguard/stellar-uri/blob/master/src/lib/transaction-stellar-uri.ts#L19

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by tyvdh** [comment]
Looks like it's an issue with node v8 not having URL at the global level. When using v10 there's no issue.

**Comment by pselden** [comment]
I'll include the polyfill directly as a dependency to avoid this for others.

**Comment by MisterTicot** [comment]
Another option could be to use [URI.js](https://www.npmjs.com/package/urijs) which is also a depend of stellar-sdk.

**Comment by pselden** [comment]
I decided not to include a polyfill, as it just bloats the download size for most users of modern browsers and NodeJS versions (8 will end LTS support in December). Developers who want to use it can still polyfill it themselves.
